---

# Set up DEX identity provider for NLX with static accounts

- set_fact:
    _nlx_dex_extra_labels:
      app.kubernetes.io/name: dex
      app.kubernetes.io/component: idp

- name: Management | Set up DEX identity provider static config
  k8s:
    state: "{{ nlx_state }}"
    name: "nlx-dex-{{ nlx_instance }}"
    namespace: "{{ nlx_namespace }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        labels: "{{ nlx_metadata_common_labels }}"
      data:
        config.yml: "{{ lookup('template', 'dex-config.yml.j2') }}"

    validate:
      fail_on_error: true
      strict: true
  register: nlx_dex_config

- name: Management | Set up DEX service
  k8s:
    state: present
    name: "nlx-dex-{{ nlx_instance }}"
    namespace: "{{ nlx_namespace }}"
    definition: "{{ lookup('template', 'dex-svc.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  vars:
    _labels: "{{ nlx_metadata_common_labels | combine(_nlx_dex_extra_labels) }}"
  when: nlx_management

- name: Management | Set up DEX identity provider deployment
  k8s:
    state: "{{ nlx_state }}"
    name: "nlx-dex-{{ nlx_instance }}"
    namespace: "{{ nlx_namespace }}"
    definition: "{{ lookup('template', 'dex.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: true
      strict: true
  vars:
    _labels: "{{ nlx_metadata_common_labels | combine(_nlx_dex_extra_labels) }}"
