---

- set_fact:
    _nlx_inway_extra_labels:
      app.kubernetes.io/name: inway
      app.kubernetes.io/component: inway

- name: Set up inway service
  k8s:
    state: present
    name: "nlx-inway-{{ nlx_instance }}"
    namespace: "{{ nlx_namespace }}"
    definition: "{{ lookup('template', 'inway-svc.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  vars:
    _labels: "{{ nlx_metadata_common_labels | combine(_nlx_inway_extra_labels) }}"
  when: nlx_inway

- name: Install inway deployment
  k8s:
    state: present
    name: "nlx-inway-{{ nlx_instance }}"
    namespace: "{{ nlx_namespace }}"
    definition: "{{ lookup('template', 'inway.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  vars:
    _labels: "{{ nlx_metadata_common_labels | combine(_nlx_inway_extra_labels) }}"
  when: nlx_inway
