---

- set_fact:
    _nlx_outway_extra_labels:
      app.kubernetes.io/name: outway
      app.kubernetes.io/component: outway

- name: Set up outway service
  k8s:
    state: "{{ nlx_state }}"
    name: "nlx-outway-{{ nlx_instance }}"
    namespace: "{{ nlx_namespace }}"
    definition: "{{ lookup('template', 'outway-svc.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  vars:
    _labels: "{{ nlx_metadata_common_labels | combine(_nlx_outway_extra_labels) }}"
  when: nlx_outway

- name: Install outway deployment
  k8s:
    state: "{{ nlx_state }}"
    name: "nlx-outway-{{ nlx_instance }}"
    namespace: "{{ nlx_namespace }}"
    definition: "{{ lookup('template', 'outway.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  vars:
    _labels: "{{ nlx_metadata_common_labels | combine(_nlx_outway_extra_labels) }}"
  when: nlx_outway
