---
- name: freeports | Copy free ports script to host
  ansible.builtin.copy:
    content: |
      #!/usr/bin/python3
      import socket
      for p in range({{ django_app_docker_port_range.start }},{{ django_app_docker_port_range.end }}):
          import socket
          s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          try:
            s.bind(("",p))
          except:
              pass
          port = s.getsockname()[1]
          s.close()
          if port != 0:
            print(p)
    dest: /tmp/freeports.py
    mode: "0700"

- name: freeports | Generate list of free ports
  ansible.builtin.command: python3 /tmp/freeports.py
  register: _django_app_docker_freeports
  no_log: true
  changed_when: false
