---

- name: Provision the volumes/persistent storage
  community.docker.docker_volume:
    name: "{{ item.name | mandatory }}"
    labels:
      maykinmedia.commonground.django_app_docker/mountpoint: "{{ item.mount | mandatory }}"
      maykinmedia.commonground.django_app_docker/mode: "{{ item.mode | mandatory }}"
  loop: "{{ django_app_docker_volumes }}"
  register: _django_app_docker_volumes
  notify:
    - print volume mountpoints

# Volumes are created as the root user by the Docker daemon. For containers dropping
# privileges, the owner must be set appropriately
- name: Set volume permissions
  file:
    path: "{{ item.volume.Mountpoint }}"
    state: directory
    owner: "{{ item.owner | default(django_app_docker_name_prefix) }}"
    group: "{{ item.group | default(django_app_docker_name_prefix) }}"
    recurse: "{{ item.recurse | default(False) }}"
    mode: "{{ item.perms | default('u=rwx,g=rx,o-rwx') }}"
  loop: "{{ _django_app_docker_volumes.results }}"
