---
- name: Print volume mountpoints
  ansible.builtin.debug:
    msg: "Volume '{{ django_app_docker_result.volume.Name }}' (mounted at {{ django_app_docker_result.volume.Mountpoint }}) created"
  loop: "{{ _django_app_docker_volumes.results }}"
  loop_control:
    loop_var: django_app_docker_result
  when: django_app_docker_result.changed is true
