---

- name: Set up nginx vhost config
  k8s:
    state: present
    name: "{{ django_app_k8s_name_prefix }}-nginx"
    namespace: "{{ django_app_k8s_namespace }}"
    definition: "{{ lookup('template', django_app_k8s_nginx_config_template) | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  when: django_app_k8s_add_nginx
