---

- name: Set up Ingress
  k8s:
    state: present
    name: "{{ django_app_k8s_name_prefix}}"
    namespace: "{{ django_app_k8s_namespace }}"
    definition: "{{ lookup('template', django_app_k8s_ingress_template) | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
