---

- name: Set up the cronjobs
  k8s:
    state: present
    name: "{{ django_app_k8s_name_prefix }}-{{ item.name | mandatory | replace('_', '-') }}"
    namespace: "{{ django_app_k8s_namespace }}"
    definition: "{{ lookup('template', 'cronjob.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  loop: "{{ django_app_k8s_cronjobs }}"
