---

- name: Create service account (sa)
  k8s:
    state: present
    name: "{{ django_app_k8s_service_account }}"
    namespace: "{{ django_app_k8s_namespace }}"
    definition:
      kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: "{{ django_app_k8s_service_account }}"
    validate:
      fail_on_error: yes
      strict: yes

- name: Create SecurityContextConstraints(scc)
  k8s:
    state: present
    name: "scc-{{ django_app_k8s_service_account }}"
    namespace: "{{ django_app_k8s_namespace }}"
    definition:
      kind: SecurityContextConstraints
      apiVersion: security.openshift.io/v1
      metadata:
        name: "scc-{{ django_app_k8s_service_account }}"
      allowPrivilegedContainer: false
      runAsUser:
        type: MustRunAsRange
        uidRangeMin: 1000
        uidRangeMax: 2000
      seLinuxContext:
        type: RunAsAny
      fsGroup:
        type: MustRunAs
        ranges:
        - min: 1000
          max: 2000
      supplementalGroups:
        type: MustRunAs
        ranges:
        - min: 1000
          max: 2000
    validate:
      fail_on_error: yes
      strict: yes

- name: Create RBAC role
  k8s:
    state: present
    name: "use-scc-{{ django_app_k8s_service_account }}"
    namespace: "{{ django_app_k8s_namespace }}"
    definition:
      kind: Role
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "use-scc-{{ django_app_k8s_service_account }}"
      rules:
        - apiGroups: ["security.openshift.io"]
          resources: ["securitycontextconstraints"]
          resourceNames: ["scc-{{ django_app_k8s_service_account }}"]
          verbs: ["use"]
    validate:
      fail_on_error: yes
      strict: yes

- name: Create RBAC rolebinding
  k8s:
    state: present
    name: "use-scc-{{ django_app_k8s_service_account }}"
    namespace: "{{ django_app_k8s_namespace }}"
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "use-scc-{{ django_app_k8s_service_account }}"
      subjects:
        - kind: ServiceAccount
          name: "{{ django_app_k8s_service_account }}"
      roleRef:
        kind: Role
        name: "use-scc-{{ django_app_k8s_service_account }}"
        apiGroup: rbac.authorization.k8s.io
    validate:
      fail_on_error: yes
      strict: yes

