---

# Set up the TLS secrets

- name: Install TLS secrets
  k8s:
    state: present
    name: "{{ django_app_k8s_name_prefix }}-tls-secrets"
    namespace: "{{ django_app_k8s_namespace }}"
    definition: "{{ lookup('template', 'tls.yml.j2') | from_yaml }}"
    validate:
      fail_on_error: yes
      strict: yes
  no_log: True
